name: Fusionpact CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build Docker images
      - name: Build Docker Images
        run: |
          docker build -t backend ./backend
          docker build -t frontend ./frontend

      # Step 4: Save Docker images (optional)
      - name: Save Docker Images
        run: |
          docker save backend -o backend.tar
          docker save frontend -o frontend.tar

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/fusionpact-devops-challenge
            docker compose down
            docker compose up -d --build

